# Generated by Django 4.2.2 on 2023-09-30 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0021_remove_ownerpostimage_owner_and_more'),
        ('groups', '0012_remove_grouppostcomment_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='группа')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'Пост в группе',
                'verbose_name_plural': 'Посты в группах',
            },
        ),
        migrations.CreateModel(
            name='OwnerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals', models.ManyToManyField(related_name='posts', to='pet_owners.animal', verbose_name='питомцы в посте')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'Пост пользователя',
                'verbose_name_plural': 'Посты пользователей',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=550, verbose_name='комментарий')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
                ('likes', models.ManyToManyField(related_name='comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.ownerpost', verbose_name='пост')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img_of_post/%Y/%m/%d/', verbose_name='изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец фото')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.ownerpost', verbose_name='пост')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img_of_post/%Y/%m/%d/', verbose_name='изображение')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='группа')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.grouppost', verbose_name='пост')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=550, verbose_name='комментарий')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
                ('likes', models.ManyToManyField(related_name='group_comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.grouppost', verbose_name='пост')),
            ],
        ),
    ]
