# Generated by Django 4.2.2 on 2023-10-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_postcomment_author_remove_postcomment_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img_of_post/%Y/%m/%d/', verbose_name='изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post', verbose_name='пост')),
            ],
        ),
        migrations.RemoveField(
            model_name='ownerpostimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ownerpostimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='GroupPostImage',
        ),
        migrations.DeleteModel(
            name='OwnerPostImage',
        ),
    ]
