# Generated by Django 4.2.2 on 2023-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='about_myself',
            field=models.TextField(blank=True, max_length=520, null=True, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='owners_photos/%Y/%m/%d/', verbose_name='фото пользователя'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата рождения пользователя'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата регистрации пользователя'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='инстаграм'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='vkontakte',
            field=models.URLField(blank=True, null=True, verbose_name='вконтакте'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='ютуб'),
        ),
    ]
