# Generated by Django 4.2.2 on 2023-07-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0002_alter_owner_about_myself_alter_owner_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='date_of_registration',
        ),
    ]
