# Generated by Django 4.2.2 on 2023-07-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0003_remove_owner_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True, verbose_name='пол'),
        ),
    ]
