# Generated by Django 4.2.2 on 2023-07-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0004_animal_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_animal_birth',
            field=models.DateField(verbose_name='дата рождения питомца'),
        ),
        migrations.AlterField(
            model_name='animalfollower',
            name='join_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата подписки'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения пользователя'),
        ),
    ]
