# Generated by Django 4.2.2 on 2023-07-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0006_alter_animalfollower_options_ownerpost_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpost',
            name='animals',
            field=models.ManyToManyField(related_name='posts', to='pet_owners.animal', verbose_name='питомцы в посте'),
        ),
        migrations.AlterField(
            model_name='ownerpost',
            name='likes',
            field=models.FloatField(default=0, verbose_name='лайки'),
        ),
        migrations.AlterField(
            model_name='ownerpost',
            name='views',
            field=models.FloatField(default=0, verbose_name='просмотры'),
        ),
    ]
