# Generated by Django 4.2.2 on 2023-07-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0007_alter_ownerpost_animals_alter_ownerpost_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerpost',
            options={'ordering': ['-date_create'], 'verbose_name': 'Пост пользователя', 'verbose_name_plural': 'Посты пользователей'},
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='animals_on_img',
        ),
    ]
