# Generated by Django 4.2.2 on 2023-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0008_alter_ownerpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpost',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='лайки'),
        ),
        migrations.AlterField(
            model_name='ownerpost',
            name='views',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
