# Generated by Django 4.2.2 on 2023-07-19 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0009_alter_ownerpost_likes_alter_ownerpost_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='ownerpost',
            name='views',
        ),
        migrations.AddField(
            model_name='ownerpost',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки'),
        ),
        migrations.AddField(
            model_name='ownerpost',
            name='views',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='просмотры'),
        ),
    ]
