# Generated by Django 4.2.2 on 2023-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0011_alter_animal_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_animal_birth',
            field=models.DateField(blank=True, verbose_name='дата рождения питомца'),
        ),
    ]
