# Generated by Django 4.2.2 on 2023-08-22 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0016_remove_postcomment_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(related_name='comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки'),
        ),
    ]
