# Generated by Django 4.2.2 on 2023-08-22 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0017_remove_postcomment_likes_postcomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор поста'),
        ),
    ]
