# Generated by Django 4.2.2 on 2023-09-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owners', '0020_rename_postimage_ownerpostimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerpostimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ownerpostimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='OwnerPost',
        ),
        migrations.DeleteModel(
            name='OwnerPostImage',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
