# Generated by Django 4.2.2 on 2023-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=150, verbose_name='название группы')),
                ('about_group', models.TextField(max_length=2000, verbose_name='инф о группе')),
                ('img_of_group', models.ImageField(upload_to='img_of_group/%Y/%m/%d/', verbose_name='лого группы')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='дата подписки')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=105, verbose_name='заголовок')),
                ('text_of_post', models.TextField(max_length=2000, verbose_name='текст поста')),
                ('is_published', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания поста')),
                ('views', models.FloatField(verbose_name='просмотры')),
                ('likes', models.FloatField(verbose_name='лайки')),
            ],
            options={
                'verbose_name': 'Пост пользователя',
                'verbose_name_plural': 'Посты пользователей',
            },
        ),
        migrations.CreateModel(
            name='GroupPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=550, verbose_name='комментарий')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('likes', models.FloatField(verbose_name='лайки')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыт')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img_of_post/%Y/%m/%d/', verbose_name='изображение')),
            ],
        ),
    ]
