# Generated by Django 4.2.2 on 2023-07-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
