# Generated by Django 4.2.2 on 2023-08-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppostimage',
            name='animals_on_img',
        ),
    ]
