# Generated by Django 4.2.2 on 2023-08-29 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_remove_grouppostimage_animals_on_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='views',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='likes',
            field=models.ManyToManyField(related_name='grp_likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='views',
            field=models.ManyToManyField(related_name='grp_views', to=settings.AUTH_USER_MODEL, verbose_name='просмотры'),
        ),
    ]
