# Generated by Django 4.2.2 on 2023-09-03 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_remove_grouppost_likes_remove_grouppost_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppostcomment',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='grouppostcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор комментария'),
        ),
    ]
