# Generated by Django 4.2.2 on 2023-09-03 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_remove_grouppostcomment_is_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppostcomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='grouppostcomment',
            name='likes',
            field=models.ManyToManyField(related_name='group_comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='лайки'),
        ),
    ]
