# Generated by Django 4.2.2 on 2023-09-04 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0007_remove_grouppostcomment_likes_grouppostcomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banned',
            field=models.ManyToManyField(related_name='banned_in_group', to=settings.AUTH_USER_MODEL, verbose_name='забаненные'),
        ),
    ]
