# Generated by Django 4.2.2 on 2023-09-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('groups', '0010_alter_group_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={'verbose_name': 'Пост в группе', 'verbose_name_plural': 'Посты в группах'},
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='text_of_post',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='views',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='пост'),
        ),
    ]
